spring:
  application:
    名字: AdGuard_Home_Rules
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      #常规 14个 在大多数设备上阻止跟踪和广告的列表
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt' #1Hosts (Lite)
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt' #1Hosts (mini)
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt' #AdGuard DNS filter
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_59.txt' #AdGuard DNS Popup Hosts filter
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_53.txt' #AWAvenue Ads Rule
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt' #Dan Pollock's List
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt' #HaGeZi's Normal Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_48.txt' #HaGeZi's Pro Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_51.txt' #HaGeZi's Pro++ Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_49.txt' #HaGeZi's Ultimate Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt' #OISD Blocklist Small
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt' #OISD Blocklist Big
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt' #Peter Lowe's Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt' #Steven Black's List
      #其它 9个 其他黑名单
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_39.txt' #Dandelion Sprout's Anti Push Notifications
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt' #Dandelion Sprout's Game Console Adblock List
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_45.txt' #HaGeZi's Allowlist Referral
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_46.txt' #HaGeZi's Anti-Piracy Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_47.txt' #HaGeZi's Gambling Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_37.txt' #No Google
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt' #Perflyst and Dandelion Sprout's Smart-TV Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_57.txt' #ShadowWhisperer's Dating List
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt' #WindowsSpyBlocker - Hosts spy rules
      #区域 17个 专注于区域广告和跟踪服务器的列表
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_29.txt' #CHN: AdRules DNS List
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_21.txt' #CHN: anti-AD
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_35.txt' #HUN: Hufilter
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_22.txt' #IDN: ABPindo
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_19.txt' #IRN: PersianBlocker list
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_43.txt' #ISR: EasyList Hebrew
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_25.txt' #KOR: List-KR DNS
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_15.txt' #KOR: YousList
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_36.txt' #LIT: EasyList Lithuania
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_20.txt' #MKD: Macedonian Pi-hole Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_13.txt' #NOR: Dandelion Sprouts nordiske filtre
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_41.txt' #POL: CERT Polska List of malicious domasters
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_14.txt' #POL: Polish filters for Pi-hole
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_17.txt' #SWE: Frellwit's Swedish Hosts File
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_26.txt' #TUR: turk-adlist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_40.txt' #TUR: Turkish Ad Hosts
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_16.txt' #VNM: ABPVN List
      #安全 15个 专用于拦截恶意软件、钓鱼或欺诈域名的列表
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt' #Phishing URL Blocklist (PhishTank and OpenPhish)
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt' #Dandelion Sprout's Anti-Malware List
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_55.txt' #HaGeZi's Badware Hoster Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_54.txt' #HaGeZi's DynDNS Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_52.txt' #HaGeZi's Encrypted DNS/VPN/TOR/Proxy Bypass
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_56.txt' #HaGeZi's The World's Most Abused TLDs
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_44.txt' #HaGeZi's Threat Intelligence Feeds
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt' #NoCoin Filter List
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_18.txt' #Phishing Army
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt' #Scam Blocklist by DurableNapkin
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_42.txt' #ShadowWhisperer's Malware List
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt' #Stalkerware Indicators List
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt' #The Big List of Hacked Malware Web Sites
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt' #uBlock₀ filters – Badware risks
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt' #Malicious URL Blocklist (URLHaus)
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOmaster  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOmaster
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domaster.txt:
        - DOmaster
      modify.txt:
        - MODIFY
